// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIza...........................',
    appId: '1:194275523640:web:4df3e12aaaef99b1153acd',
    messagingSenderId: '194275523640',
    projectId: 'lesco-crisis-app',
    authDomain: 'lesco-crisis-app.firebaseapp.com',
    storageBucket: 'lesco-crisis-app.firebasestorage.app',
    measurementId: 'G-641RSCK8BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIza......',
    appId: '1:194275523640:android:06a657a365b86f32153acd',
    messagingSenderId: '194275523640',
    projectId: 'lesco-crisis-app',
    storageBucket: 'lesco-crisis-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIza.......',
    appId: '1:194275523640:ios:f1bbcda64960f57a153acd',
    messagingSenderId: '194275523640',
    projectId: 'lesco-crisis-app',
    storageBucket: 'lesco-crisis-app.firebasestorage.app',
    iosBundleId: 'com.example.commandCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIza..............',
    appId: '1:194275523640:ios:f1bbcda64960f57a153acd',
    messagingSenderId: '194275523640',
    projectId: 'lesco-crisis-app',
    storageBucket: 'lesco-crisis-app.firebasestorage.app',
    iosBundleId: 'com.example.commandCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIza.............',
    appId: '1:194275523640:web:9a1f1ba4923f5e7d153acd',
    messagingSenderId: '194275523640',
    projectId: 'lesco-crisis-app',
    authDomain: 'lesco-crisis-app.firebaseapp.com',
    storageBucket: 'lesco-crisis-app.firebasestorage.app',
    measurementId: 'G-FE588QRHTK',
  );
}
